name: Build

on:
  workflow_dispatch:

jobs:
  build-main:
    name: Main Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - run: go version
    - run: CGO_ENABLED=0 make
    - uses: actions/upload-artifact@v1
      with:
        name: humanize-test
        path: humanize-test
